name: Debug Server Status

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    environment: tabetai-secrets
    
    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

    steps:
    - name: Debug server status
      run: |
        echo "$EC2_SSH_KEY" > private_key
        chmod 600 private_key
        
        echo "=== Checking PM2 status ==="
        ssh -i private_key -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
          pm2 status
          echo ""
          echo "=== PM2 logs for tabetai-app ==="
          pm2 logs tabetai-app --lines 20 || echo "No logs found"
          echo ""
          echo "=== Check if app directory exists ==="
          ls -la ~/app/
          echo ""
          echo "=== Check server.js file ==="
          ls -la ~/app/server.js
          echo ""
          echo "=== Check .env file ==="
          cat ~/app/.env
          echo ""
          echo "=== Try starting manually ==="
          cd ~/app && node server.js &
          sleep 3
          echo "=== Check what's running on port 8080 ==="
          netstat -tlnp | grep 8080 || echo "Nothing on port 8080"
        EOF
        
        rm -f private_key
