name: Debug Secrets

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check which secrets are available
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        SPOONACULAR_API_KEY: ${{ secrets.SPOONACULAR_API_KEY }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      run: |
        echo "Checking secrets (showing only if they exist):"
        echo "EC2_HOST: ${EC2_HOST:+SET}"
        echo "EC2_USER: ${EC2_USER:+SET}"  
        echo "EC2_SSH_KEY: ${EC2_SSH_KEY:+SET}"
        echo "MONGODB_URI: ${MONGODB_URI:+SET}"
        echo "SPOONACULAR_API_KEY: ${SPOONACULAR_API_KEY:+SET}"
        echo "GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:+SET}"
        
        echo "Missing secrets:"
        [ -z "$EC2_HOST" ] && echo "❌ EC2_HOST is missing"
        [ -z "$EC2_USER" ] && echo "❌ EC2_USER is missing"
        [ -z "$EC2_SSH_KEY" ] && echo "❌ EC2_SSH_KEY is missing"
        [ -z "$MONGODB_URI" ] && echo "❌ MONGODB_URI is missing"
        [ -z "$SPOONACULAR_API_KEY" ] && echo "❌ SPOONACULAR_API_KEY is missing"
        [ -z "$GOOGLE_CLIENT_ID" ] && echo "❌ GOOGLE_CLIENT_ID is missing"
