name: Direct SSH Test

on:
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    environment: tabetai-secrets
    
    steps:
    - name: Test SSH without secrets (hardcoded)
      run: |
        echo "Testing direct SSH connection..."
        
        # Create a test SSH key file (we'll use your real one)
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key
        chmod 600 private_key
        
        # Test if the key file was created
        if [ -s private_key ]; then
          echo "SSH key file created successfully"
          echo "Key file size: $(wc -c < private_key) bytes"
          echo "First line: $(head -1 private_key)"
        else
          echo "SSH key file is empty - secret not injected"
        fi
        
        # Try to connect (will fail but show us the error)
        ssh -i private_key -o StrictHostKeyChecking=no -o ConnectTimeout=10 \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo 'Connection successful'" || echo "SSH failed - this is expected for testing"
        
        rm -f private_key
