name: Test Secrets

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ '.github/workflows/test-secrets-debug.yml' ]

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test secret availability
      run: |
        echo "Testing secrets availability..."
        echo "EC2_HOST: ${{ secrets.EC2_HOST != '' && 'SET' || 'NOT SET' }}"
        echo "EC2_USER: ${{ secrets.EC2_USER != '' && 'SET' || 'NOT SET' }}"
        echo "EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY != '' && 'SET' || 'NOT SET' }}"
        echo "MONGODB_URI: ${{ secrets.MONGODB_URI != '' && 'SET' || 'NOT SET' }}"
        echo "SPOONACULAR_API_KEY: ${{ secrets.SPOONACULAR_API_KEY != '' && 'SET' || 'NOT SET' }}"
        echo "GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID != '' && 'SET' || 'NOT SET' }}"
        
        # Test lengths (without exposing values)
        echo "EC2_HOST length: ${#EC2_HOST}"
        echo "EC2_USER length: ${#EC2_USER}"
        echo "SSH key length: ${#EC2_SSH_KEY}"
        echo "MongoDB URI length: ${#MONGODB_URI}"
        echo "Spoonacular key length: ${#SPOONACULAR_API_KEY}"
        echo "Google client ID length: ${#GOOGLE_CLIENT_ID}"
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        SPOONACULAR_API_KEY: ${{ secrets.SPOONACULAR_API_KEY }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        
    - name: Test SSH key format
      run: |
        echo "Testing SSH key format..."
        if [[ "$EC2_SSH_KEY" == *"BEGIN"* && "$EC2_SSH_KEY" == *"END"* ]]; then
          echo "✅ SSH key appears to have correct format"
        else
          echo "❌ SSH key format might be incorrect"
          echo "SSH key should start with -----BEGIN and end with -----END"
        fi
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        
    - name: Test MongoDB URI format
      run: |
        echo "Testing MongoDB URI format..."
        if [[ "$MONGODB_URI" == *"mongodb"* ]]; then
          echo "✅ MongoDB URI appears to have correct format"
        else
          echo "❌ MongoDB URI format might be incorrect"
          echo "Should start with mongodb:// or mongodb+srv://"
        fi
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        
    - name: Test Google Client ID format
      run: |
        echo "Testing Google Client ID format..."
        if [[ "$GOOGLE_CLIENT_ID" == *".apps.googleusercontent.com" ]]; then
          echo "✅ Google Client ID appears to have correct format"
        else
          echo "❌ Google Client ID format might be incorrect"
          echo "Should end with .apps.googleusercontent.com"
        fi
      env:
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
