name: Test Secrets Only

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test if secrets work at all
      run: |
        echo "Testing basic secret access..."
        echo "Repository: ${{ github.repository }}"
        echo "Actor: ${{ github.actor }}"
        echo "Event: ${{ github.event_name }}"
        
        # Test with a simple secret check
        SECRET_TEST="${{ secrets.EC2_HOST }}"
        if [ -z "$SECRET_TEST" ]; then
          echo "FAILURE: EC2_HOST secret is completely empty"
          echo "This indicates a GitHub Actions configuration issue"
        else
          echo "SUCCESS: EC2_HOST secret is available"
          echo "Length: ${#SECRET_TEST}"
        fi
        
        # Check repository settings
        echo "Workflow run ID: ${{ github.run_id }}"
        echo "Repository owner: ${{ github.repository_owner }}"
